package enums

const (
	APP_NAME = "APP_NAME"
	ENV      = "ENV"
	PORT     = "PORT"
	TIMEZONE = "TIMEZONE"
)

const (
	MODE = "MODE"
)

const (
	DEV        = "DEV"
	PRODUCTION = "PRODUCTION"
)

const (
	DEBUG      = "DEBUG"
	VERSION    = "VERSION"
	COMMIT_SHA = "COMMIT_SHA"

	RELEASE_URL = "RELEASE_URL"
)

const (
	APP_LOG_FILE_FORMAT = "APP_LOG_FILE_FORMAT"
	STD_REPO_URI        = "STD_REPO_URI"

	STD_MODULE_PREFIX = "STD_MODULE_PREFIX"

	STD_MODULE_FORMAT = STD_REPO_URI + STD_MODULE_PREFIX + "-%s"
)

const (
	APP_DIR      = "app_dir"
	APP_DATA_DIR = "app-data-dir"
	MODULE_PATH  = "MODULE_PATH"

	APP_PLUGIN_DIR = "app-plugin-dir"
)

const (
	JOBCREATOR_OPTION_INPUT = "i"
)

const (
	DEALER      = "dealer"
	DEALER_PATH = "dealer-path"
)

const (
	COOPHIVE_CONTROLLER_ADDRESS = "coophive_controller_address"
	WEB3_PAYMENTS_ADDRESS       = "WEB3_PAYMENTS_ADDRESS"

	WEB3_STORAGE_ADDRESS = "WEB3_STORAGE_ADDRESS"
	WEB3_USERS_ADDRESS   = "WEB3_USERS_ADDRESS"

	WEB3_TOKEN_ADDRESS = "WEB3_TOKEN_ADDRESS"

	WEB3_MEDIATION_ADDRESS = "WEB3_MEDIATION_ADDRESS"

	WEB3_JOBCREATOR_ADDRESS = "WEB3_JOBCREATOR_ADDRESS"
)
