// Code generated by "stringer -type=FeatureFlag --trimprefix=FeatureFlag -linecomment -output=featureFlags_string.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PanicIfResultNotFound-0]
}

const _FeatureFlag_name = "PanicIfResultNotFound"

var _FeatureFlag_index = [...]uint8{0, 21}

func (i FeatureFlag) String() string {
	if i < 0 || i >= FeatureFlag(len(_FeatureFlag_index)-1) {
		return "FeatureFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FeatureFlag_name[_FeatureFlag_index[i]:_FeatureFlag_index[i+1]]
}
