// Code generated by "stringer -type=ServiceType  -linecomment -output=serviceType_string.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[JC-0]
	_ = x[RP-1]
	_ = x[SOLVER-2]
	_ = x[MEDIATOR-3]
}

const _ServiceType_name = "JCRPSOLVERMEDIATOR"

var _ServiceType_index = [...]uint8{0, 2, 4, 10, 18}

func (i ServiceType) String() string {
	if i < 0 || i >= ServiceType(len(_ServiceType_index)-1) {
		return "ServiceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServiceType_name[_ServiceType_index[i]:_ServiceType_index[i+1]]
}
