version: '3.8'
services:
  aurora:
    environment:
      FAUCET_PORT: 8080
      NETWORK: "aurora"
    env_file:
      - .env.aurora
    image: ghcr.io/coophive/faucet:latest
    restart: always
    ports:
      - 8080:${FAUCET_PORT}
    healthcheck:
      test: [ 'CMD', 'curl', '--fail', 'http://localhost:${FAUCET_PORT}' ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  sepolia:
    environment:
      FAUCET_PORT: 8080
      NETWORK: "sepolia"
    env_file:
      - .env.sepolia
    image: ghcr.io/coophive/faucet:latest
    restart: always
    ports:
      - 8081:${FAUCET_PORT}
    healthcheck:
      test: [ 'CMD', 'curl', '--fail', 'http://localhost:${FAUCET_PORT}' ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  calibration:
    environment:
      FAUCET_PORT: 8080
      NETWORK: "calibration"
    env_file:
      - .env.calibration
    image: ghcr.io/coophive/faucet:latest
    restart: always
    ports:
      - 8082:${FAUCET_PORT}
    healthcheck:
      test: [ 'CMD', 'curl', '--fail', 'http://localhost:${FAUCET_PORT}' ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s