version: "3.8"

services:
  #  jc:
  #    image: ghcr.io/coophive/hive:latest
  #    command: [ "jc" ]
  #    restart: always
  #    healthcheck:
  #      test: [ "CMD", "./bin/hive", "jc", "--help" ]
  #      interval: 10s
  #      timeout: 5s
  #      retries: 3
  #      start_period: 10s
  #    volumes:
  #      - ./data:/app/coophive

  #  mediator:
  #    env_file:
  #      - .env
  #    image: ghcr.io/coophive/hive:latest
  #    command: [ "mediator" ]
  #    restart: always
  #    healthcheck:
  #      test: [ "CMD", "./bin/hive", "mediator", "--help" ]
  #      interval: 10s
  #      timeout: 5s
  #      retries: 3
  #      start_period: 10s
  #    volumes:
  #      - ./data:/app/coophive

  rp:
    image: ghcr.io/coophive/hive:latest
    command: [ "rp" ]
    restart: always
    healthcheck:
      test: [ "CMD", "./bin/hive", "rp", "--help" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ./data:/app/coophive

  #  run:
  #    image: ghcr.io/coophive/hive:latest
  #    command: [ "run" ]
  #    restart: always
  #    healthcheck:
  #      test: [ "CMD", "./bin/hive", "run", "--help" ]
  #      interval: 10s
  #      timeout: 5s
  #      retries: 3
  #      start_period: 10s
  #    volumes:
  #      - ./data:/app/coophive

  solver:
    image: ghcr.io/coophive/hive:latest
    command: [ "solver" ]
    restart: always
    healthcheck:
      test: [ "CMD", "./bin/hive", "solver", "--help" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ./data:/app/coophive

#  version:
#    image: ghcr.io/coophive/hive:latest
#    command: [ "version" ]
#    restart: always
#    healthcheck:
#      test: [ "CMD", "./bin/hive", "version" ]
#      interval: 10s
#      timeout: 5s
#      retries: 3
#      start_period: 10s
#    volumes:
#      - ./data:/app/coophive
