version: '3.8'
services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    healthcheck:
      test: [ 'CMD', './bin/hive', 'version' ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
#    volumes:
#      - ./temp:/app