name: Hardhat [Docker]

on:
  push:
    branches:
      - main
    tags:

  pull_request:
    branches:

  merge_group:
    types: [ checks_requested ]

  workflow_dispatch:

defaults:
  run:
    working-directory: ./hardhat

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  envfile: ${{secrets.ENV}}
  MODE: test
  NODE_ENV: testing
  DOTENV_CONFIG_PATH: './hardhat/.env'

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker
        run: docker build .
