name: Hardhat Contracts [Test]

on:
  push:

  pull_request:

  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./hardhat

env:
  envfile: ${{secrets.ENV}}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.6

      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          cache-dependency-path: "./hardhat/pnpm-lock.yaml"
          node-version: "20.9.0"
          check-latest: true

      - name: Write environment
        run: |
          echo $envfile > .env
          sed -i 's/ /\n/g' .env
          source .env

      - name: Install dependencies
        run: pnpm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Test
        run: npx hardhat test
