name: Docker

on:
  push:
    branches:
      - main

    tags:

  pull_request:
    branches:
      - main
  merge_group:
    types: [ checks_requested ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  envfile: ${{secrets.ENV}}
  MODE: test
  NODE_ENV: testing
  CONFIG: "./hardhat/.env"

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker
        run: docker build .

  test-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Write environment
        run: |
          echo $envfile > .env.tmp
          sed 's/ /\n/g' .env.tmp > .env
          source .env
          cp .env .env.test

      - name: Build Docker
        run: docker build -t app .
#TODO: docker create Dockerfile.test
