name: Publish to GCR
on:
  push:
    branches:

    tags:

  pull_request:

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PUSH_TAG: ${{github.repository}}:latest
  REPO: ${{github.repository}}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      #          fetch-tags: true

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

          # https://github.com/marketplace/actions/docker-metadata-action#images-input
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          # base for tags
          images: |
            ${{ env.REGISTRY }}/${{env.IMAGE_NAME}}
            ${{ env.REGISTRY}}/${{github.repository_owner}}/hive
            ${{ env.REGISTRY}}/${{github.repository_owner}}/coophive
            ${{ env.REGISTRY}}/${{github.repository_owner}}/coophiveV0
            ${{ env.REGISTRY}}/${{github.repository_owner}}/coophive-v0

          tags: |
            type=schedule
            type=sha,format=short

            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr

            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Evaluate all tags
        run: |

          echo meta tags
          echo "${{ steps.meta.outputs.tags }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels}}
          github-token: ${{github.token}}
#      - name: Build and push MultiArch Docker image
#        uses: docker/build-push-action@v5
#        with:
#          context: multiArch.Dockerfile
#          push: ${{ github.event_name != 'pull_request' }}
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels}}
#          github-token: ${{github.token}}
#          platforms: linux/arm64,linux/amd64,linux/arm/v7,darwin #TODO:https://docs.docker.com/build/ci/github-actions/multi-platform/
#

# cache-from: type=gha
# FIXME: enable cache
# cache-to: type=gha,mode=max
# https://github.com/docker/metadata-action/tree/v4/
