name: Release

on:
  pull_request:
  push:
    tags:
      - '*'
      - '**'

    branches:
      - main
      - release/*

permissions:
  contents: write

jobs:
  #  FIXME: disabled cuz u need to delete the release that was created on the tag for overwriting
  genr-tags-branch:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/heads/release/')

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 3

      - name: For Branches
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          BRANCH_NAME=${BRANCH_NAME//\//-}
          git tag "$BRANCH_NAME" -f
          git push --tags -f

  genr-tags-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: For PRs
        if: github.event_name == 'pull_request'
        run: |
          PR_NUMBER=$(echo "$GITHUB_REF" | awk -F / '{print $3}')
          PR_TAG="$PR_NUMBER-pr"
          git tag "$PR_TAG" -f
          git push --tags -f

  goreleaser:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          ref: ${{ github.event.ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true
      
      #      - name: PreRelease
      #        if: github.event_name == 'pull_request'
      #        run: |
      #          #pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
      #          PR_NUMBER=$(echo "$GITHUB_REF" | awk -F / '{print $3}')
      #          PR_TAG="$PR_NUMBER-pr"
      #          git tag "$PR_TAG" -f
      #          export VERSION=$(git describe --tags --abbrev=0)-$PR_TAG
      #          export COMMIT_SHA=$(git rev-parse HEAD)
      - name: PreRelease
        if: github.event_name != 'pull_request'
        run: |
          export VERSION=$(git describe --tags --abbrev=0)
          export COMMIT_SHA=$(git rev-parse HEAD)
      

      - name: Run GoReleaser
        continue-on-error: true
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        #          workdir:
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: hive
          path: ./dist/*
