name: Release

on:
  push:
    tags:


permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 3
          ref: ${{ github.event.ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Get Tag
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set Tag output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - uses: nowsprinting/check-version-format-action@v4
        id: version
        with:
          prefix: "v"

      - name: Version tag only step
        run: |
          echo "Found valid version format in tag!"
          echo "Full version: ${{ steps.version.outputs.full }}"
          echo "Major version: ${{ steps.version.outputs.major }}"
          echo "Major with pre-release: ${{ steps.version.outputs.major_prerelease }}"
        if: steps.version.outputs.is_valid == 'true'

      - name: Stable version only step
        run: |
          echo "Found stable version in tag!"
        if: steps.version.outputs.is_stable == 'true'


      - name: Goreleaser Args
        id: goreleaser-args
        run: |
          args=()
          
          if [[ "${{ steps.version.outputs.is_valid }}" == "false" && "${{steps.vars.outputs.tag}}"!="latest" ]]; then
            args+='--snapshot'
          fi
          
          echo "Args is $args"
          echo "args=$args" >> $GITHUB_OUTPUT

      - name: Run GoReleaser
        continue-on-error: true
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          install-only: false

          args: |
            release --clean ${{ steps.goreleaser-args.args }}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: hive
          path: ./dist/*
